# Generated by Django 4.2.5 on 2023-10-08 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_users_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
    ]
